# ===================================
# NOME DA APLICAÇÃO
# ===================================

spring.application.name=auth-api

# ===================================
# CONFIGURAÇÃO DO BANCO H2
# ===================================

# URL do banco em memória
spring.datasource.url=jdbc:h2:mem:testdb

# Driver do H2
spring.datasource.driverClassName=org.h2.Driver

# Usuário padrão
spring.datasource.username=sa

# Senha vazia
spring.datasource.password=

# ===================================
# H2 CONSOLE
# ===================================

# Ativa painel web do H2
spring.h2.console.enabled=true

# Caminho do console
spring.h2.console.path=/h2-console

# ===================================
# JPA / HIBERNATE
# ===================================

# Atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL no terminal
spring.jpa.show-sql=true